name: macOS
on: [push, pull_request]
jobs:
  lint-code:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install pylint
      - run: cd test; ./lint.sh
  ci-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install icarus-verilog
      - run: iverilog -V
      - run: brew install verilator
      - run: verilator -V
      - run: cd test; ./regression.sh
